{% set name = "anyascii" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anyascii-{{ version }}.tar.gz
  sha256: dedf57728206e286c91eed7c759505a5e45c8cd01367dd40c2f7248bb15c11f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - anyascii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anyascii/anyascii
  summary: Unicode to ASCII transliteration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
