{% set name = "anyascii" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anyascii-{{ version }}.tar.gz
  sha256: 9d5d32ef844fe225b8bc7cba7f950534fae4da27a9bf3a6bea2cb0ea46ce4730

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - anyascii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anyascii/anyascii
  summary: Unicode to ASCII transliteration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
